package com.muravskyi.spring.section03_hibernate;

import com.muravskyi.spring.section03_hibernate.entity.Employee;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class HibernateExample {

    private static final Logger LOGGER = LogManager.getLogger();

    public static void main(String[] args) {

        try (
            SessionFactory factory = new Configuration()
                .configure("hibernate.cfg.xml")
                .addAnnotatedClass(Employee.class)
                .buildSessionFactory()
        ) {
            // Get created session in configuration. Can be used same session all around the application.
            Session session = factory.getCurrentSession();

            Employee emp = new Employee("Volodymyr", "Muravskyi", "IT", 1500);

            // always open transaction and commit at the end
            session.beginTransaction();
            // hibernate will add "ID" generated by database to this object
            session.save(emp);
            session.getTransaction().commit();

            LOGGER.info("ID returned from DB: {}", emp.getId());
        }
        // make sure to close factory
        // using try with resources
    }

}
