package com.muravskyi.spring.section03_hibernate;

import com.muravskyi.spring.section03_hibernate.entity.Employee;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.Test;

public class HibernateTest {

    private SessionFactory factory;
    private Session session;

    @Test
    void test1() {
        factory = new Configuration()
            .configure("hibernate.cfg.xml")
            .addAnnotatedClass(Employee.class)
            .buildSessionFactory();

        try {
            // Get created session in configuration. Can be used same session all around the application.
            session = factory.getCurrentSession();

            Employee emp = new Employee("Volodymyr", "Muravskyi", "IT", 1500);

            // always open transaction and commit at the end
            session.beginTransaction();
            // hibernate will add "ID" generated by database to this object
            session.save(emp);
            session.getTransaction().commit();
        } finally {
            // make sure to close factory
            factory.close();
        }
    }

}
