package com.muravskyi.spring.section03_hibernate.hibernatetest1;

import com.muravskyi.spring.section03_hibernate.hibernatetest1.entity.Employee;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.Test;

public class HibernateTest2Save {

    private Logger LOGGER = LogManager.getLogger();

    @Test
    void testEmployee() {
        SessionFactory factory = new Configuration()
            .configure("hibernate.cfg.xml")
            .addAnnotatedClass(Employee.class)
            .buildSessionFactory();

        try {
            // Get created session in configuration. Can be used same session all around the application.
            Session session = factory.getCurrentSession();

            Employee emp = new Employee("Bruce", "Li", "Support", 1150);

            // always open transaction and commit at the end
            session.beginTransaction();
            // hibernate will add "ID" generated by database to this object
            session.save(emp);

            int empId = emp.getId();
            Employee employee = session.get(Employee.class, empId);
            session.getTransaction().commit();
            session.close();

            System.out.println(employee);
        } finally {
            // make sure to close factory
            factory.close();
        }
    }

}
